import type { StorageAnalysisState, StorageOverviewResponse } from "@/lib/types/system";

export const degradedOverview = {
  settings: {
    enabled: false,
    check_interval_hours: 24,
    idle_for_minutes: 10,
    orphan_grace_hours: 168,
    quarantine_retention_hours: 168,
    workspaces: { enabled: true, dependency_cleanup_enabled: false },
    kandev_containers: { enabled: true },
    go_cache: {
      enabled: false,
      max_bytes: 16106127360,
      adopted_path: "",
      allow_cleanup_while_busy: false,
    },
    docker: {
      dedicated_daemon_acknowledged: false,
      build_cache_enabled: false,
      build_cache_keep_bytes: 10737418240,
      build_cache_unused_hours: 168,
      unused_images_enabled: false,
      unused_images_hours: 168,
    },
  },
  capabilities: {
    managed_go_cache_path: "/data/cache/go-build",
    go_cache_adoption_available: true,
    temporary_artifacts_available: false,
    docker_available: false,
    docker_host: "",
    host_global_docker_cleanup_allowed: false,
  },
  summary: {
    workspaces: { active_bytes: 0, candidate_bytes: 0 },
    go_cache: {
      path: "/data/cache/go-build",
      size_bytes: 0,
      cleanup_eligible_size_bytes: 0,
      owned: true,
      enabled: false,
    },
    quarantine: { available: false, warning: "quarantine database unavailable" },
    temporary_artifacts: { available: false, warning: "temporary artifact registry unavailable" },
    docker: {
      available: false,
      build_cache_bytes: 0,
      unused_image_bytes: 0,
      managed_container_count: 0,
      managed_container_bytes: 0,
    },
  },
  analysis: {
    generation: 1,
    state: "ready",
    started_at: "2026-07-23T11:59:00Z",
    completed_at: "2026-07-23T12:00:00Z",
    duration_ms: 60000,
    cache_ttl_seconds: 900,
    refresh_due_at: "2099-07-23T12:15:00Z",
    stale: false,
    error: null,
    progress: { completed_sources: 8, total_sources: 8, sources: {} },
    partial_summary: null,
  } satisfies StorageAnalysisState,
  analyzed_at: "2026-07-23T12:00:00Z",
  last_run: null,
} satisfies StorageOverviewResponse;
